[package]
name = "esso-rust"
version = "0.1.0"
authors = ["George Rogers <grogers385@gmail.com>"]

[dependencies]
handlebars-iron = "*"
iron = "*"
router = "*"
mount = "*"
params = "*"
rustc-serialize = "*"
staticfile = "*"
